### ISSUE TITLE
TwiCIL should use TLS/SSL

### ISSUE THREAD

**Issue by issork** [drtwisted/godot-twicil#3]
This is a security risk, connection is being established to the plain-text irc port 6667 and not to the TLS/SSL port 6697.

Furthermore, cert verification and such should be happening.

**Comment by drtwisted** [comment]
@MennoMax it's planned to use new `HTTPRequest` wrapper class introduced in Godot Engine 3.1. This should bring the support of TLS/SSL via native engine means. Anyways that is considered.

**Comment by issork** [comment]
Good to hear!

I recommend using the new WebSocketClient instead.

**Comment by programnoir** [comment]
Saw a recent commit and wanted to say thanks for continuing work on this, drtwisted. I have a game in development that is using this, but yeah the TLS and SSL stuff sounds like something that I hope is covered soon. I absolutely would love to try to contribute and figure this out, but oh man, this stuff is beyond me, it just is.

Like, WebSocketClient seems to verify SSL, but how would you handle TLS? I searched the docs for TLS and it recommended this topic: https://docs.godotengine.org/en/3.1/tutorials/networking/ssl_certificates.html#doc-ssl-certificates but it doesn't mention anything about TLS. I wouldn't even know how to code it. It lists the methods and what they do, kinda? But as far as practically using it, I wouldn't even know where to start. Part of me wonders if it's like you add a WebSocketClient node of some kind?

The tutorials on youtube explain things like hosting/joining games and downloading a quick block of json but nothing is mentioned about SSL. If you end up doing this branch I'll pretty much be pouring over the code and learning all that I can ahaha. Honestly like if there is some reading you recommend I would really like to try to catch up somehow.

**Comment by issork** [comment]
TLS basically replaced SSL a while ago, the term SSL is however still sometimes used for it. I have written a fully functional yet less easily modifiable twitch bot to test the web socket back when I opened this issue. I can send you my implementation if you want.

**Comment by programnoir** [comment]
I didn't know TLS was a replacement for SSL! The more you know ahaha. I should learn the differences between the two, in that case. I'd love to see it, thank you. I actually opened a bounty on the official Godot discord for whoever contributes this feature, like as a pull request at least. If you can do that, the $50 is yours. Ideally if you *can* make it easily modifiable (at least as modifiable as the things in the rest of this project is) that'd be sweet.

**Comment by drtwisted** [comment]
@nitronova hi, thanks for the interest in the project! Hope your game'll do well! I'm not that much of a network guy, @MennoMax is better at this I guess:-). I'm currently working on THE issue. And for the moment, I've managed to establish a connection, send and receive commands. There is something fundamentally wrong with sending though. Because all I get when sending commands to server is
```
 :tmi.twitch.tv 421 you
```
Which, according to twitch dev documentation, means server didn't recognize the command.

So any help with this would be much appreciated!

**Comment by issork** [comment]
I can send you my old implementation as well over discord (if I can find you there) but also started working on a more general implementation called "GIFT" (Godot IRC For Twitch)

**Comment by drtwisted** [comment]
@MennoMax I go in discord by @PanHooHa, would be much obliged!

UPD: I did it guys! It was just too late and my brain just dried out, I guess. It works now!
So you should wait for some massive update soon!

**Comment by drtwisted** [comment]
@nitronova hi! btw, is there any test-alpha builds or maybe website/page I can have a look at what you're working on? :-)

**Comment by programnoir** [comment]
You'll get a message from someone named Tony shortly!

**Comment by drtwisted** [comment]
That's finally closed, currently the code is available in [godot3.1 branch](https://github.com/drtwisted/godot-twicil/tree/godot3.1).
A bit latter I'll uploaded to the AssetLib and prepare a proper release as well. Thanks you, guys!
